### ISSUE TITLE
Decrypt not working

### ISSUE THREAD

**Issue by anuradhabandara** [h0rn3t/xxtea#10]
![image](https://user-images.githubusercontent.com/6284891/109793483-b580da00-7c3a-11eb-9f6d-5846d16af180.png)

![image](https://user-images.githubusercontent.com/6284891/109795469-fb3ea200-7c3c-11eb-9ef1-c658c6d54713.png)

**Comment by h0rn3t** [comment]
@anuradhabandara wrong position of password argument

**Comment by h0rn3t** [comment]
```
import {encrypt, decrypt } from './lib/xxtea.js'


const password = 'test';
let test = encrypt('JSON.stringify(values)', password);
console.log(test);
test = decrypt(test, password)
console.log(test);
```

**Comment by h0rn3t** [comment]
all working fine
