### ISSUE TITLE
is ready to production ?

### ISSUE THREAD

**Issue by jt3k** [h0rn3t/xxtea#5]

**Comment by jt3k** [comment]
i found a bugs with russian letters
```js
// with English
data = xxtea.encrypt('Hi!', 'hello');
xxtea.decrypt(data, 'hello'); // =>"Hi!"

// with Russian
data = xxtea.encrypt('Привет!', 'hello');
xxtea.decrypt(data, 'hello') // =>"D<65F%"
```

**Comment by h0rn3t** [comment]
fixed in 0.2.0

**Comment by jt3k** [comment]
thnx

**Comment by h0rn3t** [comment]
@jt3k вообще странно у меня на продакшене это с русским работает нормально  и без фикса ))))

**Comment by jt3k** [comment]
Видимо ваш продакшен привык уже ))

![2017-04-07 20 26 09](https://cloud.githubusercontent.com/assets/1261240/24811899/a757dba0-1bd0-11e7-9696-8c061fe8f529.png)

**Comment by h0rn3t** [comment]
да у меня cp1251 на том сервере

2017-04-07 20:28 GMT+03:00 Andrey Gurtovoy <notifications@github.com>:
